version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - VERSION="${MAJOR}.$(date +%j).${CODEBUILD_BUILD_NUMBER}"
  build:
    commands:
      - dotnet build 
  post_build:
    commands:
      - dotnet nuget push YadaYada.CropperJs/bin/Debug/*.nupkg --api-key $NUGET_API_KEY  --source https://api.nuget.org/v3/index.json